name: update schedule 2:00

on:
  schedule:
    - cron: '0 2 * * *'  # Trigger daily at 2:00 UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote repository
        run: git remote add upstream https://github.com/vbskycn/iptv.git

      - name: Pull latest changes
        run: |
          set -e  # Exit on error
          git fetch upstream
          git merge upstream/master --strategy=recursive --strategy-option=theirs --allow-unrelated-histories || { echo 'Merge failed'; exit 1; }

      - name: Reset workflow files to avoid pushing
        run: |
          git checkout HEAD -- .github/workflows/

      - name: Determine target branch
        id: vars
        run: |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Push changes
        run: |
          TARGET_BRANCH=${{ env.BRANCH_NAME }}
          if [[ "$TARGET_BRANCH" == "master" ]]; then
            git push origin master || { echo 'Push to master failed'; exit 1; }
          elif [[ "$TARGET_BRANCH" == "main" ]]; then
            git push origin main || { echo 'Push to main failed'; exit 1; }
          else
            echo "No matching branch to push."
            exit 0
          fi
